import esbuild from "esbuild";
import process from "process";
import { builtinModules } from "node:module";

// Mark Node's built-in modules (with and without the `node:` prefix) as external.
const builtins = [...builtinModules, ...builtinModules.map((m) => `node:${m}`)];

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.tsx"],
	bundle: true,
	// Bundle Preact in place of React (smaller, and avoids react-dom's
	// resource-hoisting code paths). Types still resolve against @types/react.
	alias: {
		"react": "preact/compat",
		"react-dom": "preact/compat",
		"react-dom/client": "preact/compat/client",
		"react/jsx-runtime": "preact/jsx-runtime",
		"react/jsx-dev-runtime": "preact/jsx-dev-runtime",
	},
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtins],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
	minify: prod,
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
