name: Create Release

on:
  pull_request:
    types:
      - closed
    branches:
      - master

jobs:
  create-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    if: github.event.pull_request.merged == true

    steps:
      - name: Check branch name pattern
        run: |
          BRANCH_NAME="${{ github.event.pull_request.head.ref }}"
          if [[ ! "$BRANCH_NAME" =~ ^release/(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)(-(0|[1-9A-Za-z-][0-9A-Za-z-]*)(\.[0-9A-Za-z-]+)*)?(\+[0-9A-Za-z-]+(\.[0-9A-Za-z-]+)*)?$ ]]; then
            echo "Branch name does not match the pattern: $BRANCH_NAME"
            exit 0
          else
            echo "Branch name matches the pattern: $BRANCH_NAME"
          fi

      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Extract version from branch name
        id: extract_version
        run: echo "VERSION=${GITHUB_HEAD_REF#release/}" >> $GITHUB_OUTPUT

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"

      - name: Build plugin
        run: |
          npm install
          npm run build

      - name: Create Tag
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git tag ${{ steps.extract_version.outputs.VERSION }}
          git push origin ${{ steps.extract_version.outputs.VERSION }}

      - name: Create Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create ${{ steps.extract_version.outputs.VERSION }} \
            --title="${{ steps.extract_version.outputs.VERSION }}" \
            --generate-notes \
            main.js manifest.json styles.css