name: Create Release

on:
  pull_request:
    types:
      - closed
    branches:
      - master

jobs:
  validate-branch:
    uses: ./.github/workflows/validate-branch.yml

  create-release:
    needs: validate-branch
    if: |
      github.event.pull_request.merged == true &&
      needs.validate-branch.outputs.is_valid == 'true'
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Extract version from branch name
        id: extract_version
        run: echo "VERSION=${GITHUB_HEAD_REF#release/}" >> $GITHUB_OUTPUT

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"

      - name: Build plugin
        run: |
          npm install --force # force install to use react 19 with react-datepicker
          npm run build

      - name: Create Tag
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git tag ${{ steps.extract_version.outputs.VERSION }}
          git push origin ${{ steps.extract_version.outputs.VERSION }}

      - name: Create Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create ${{ steps.extract_version.outputs.VERSION }} \
            --title="${{ steps.extract_version.outputs.VERSION }}" \
            --generate-notes \
            main.js manifest.json styles.css